  traefik:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: "traefik:v2.2"
    container_name: "traefik"
    networks:
      npm_proxy:
        ipv4_address: 192.168.89.254 # You can specify a static IP
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      # - target: 8080 # insecure api wont work
      #   published: 8080
      #   protocol: tcp
      #   mode: host
    volumes:
     - $DOCKERDIR/appdata/traefik/traefik.toml:/traefik.toml
     - $DOCKERDIR/appdata/traefik/traefik_dynamic.toml:/traefik_dynamic.toml
     - /var/run/docker.sock:/var/run/docker.sock:ro
     # - /var/run/docker.sock:/var/run/docker.sock:ro # Use Docker Socket Proxy instead for improved security
     - $DOCKERDIR/appdata/traefik/acme/acme.json:/acme.json # cert location - you must create this emtpy file and change permissions to 600